version: 0.0
os: linux
files: 
    - source: /
hooks:
    BeforeInstall:
        - location: scripts/before_install
        timeout: 300
        runas: root
    AfterInstall: 
        - location: scripts/after_intsall
        timeout: 300
        runas: root