version: 0.2

run-as: ec2-user 

phases: 
    pre_build: 
        - echo Stopping and removing containers...
        - sudo docker-compose down -v 
    build:
        - echo Building new images...
        - sudo docker-compose build
    post_build:
        - echo Starting app...
        - sudo docker-compose up & 
