version: '3'
services:
  app:
    image: 171754680472.dkr.ecr.us-east-1.amazonaws.com/forest-app
    command: >
      sh -c "python manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000:8000
    environment:
      - DEBUG=0
      - SECRET_KEY=supersecretkey
      - DJANGO_ALLOWED_HOSTS=*
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

  nginx:
    image: 171754680472.dkr.ecr.us-east-1.amazonaws.com/forest-app-nginx
    ports:
      - 80:80
    depends_on:
      - app

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
