# Generated by Django 2.1.15 on 2020-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200113_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('land_owner', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('metric_system', models.BooleanField(default=True)),
            ],
        ),
    ]
