# Generated by Django 2.1.15 on 2020-01-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='identification',
            field=models.IntegerField(unique=True),
        ),
    ]
