# Generated by Django 2.1.15 on 2020-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('max_density_index', models.FloatField()),
            ],
        ),
    ]
