# Generated by Django 2.1.15 on 2020-01-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_treereference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('dbh', models.FloatField()),
                ('height', models.FloatField()),
                ('live_crown_ratio', models.FloatField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plot')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TreeReference')),
            ],
        ),
    ]
