# Generated by Django 2.1.15 on 2020-01-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200120_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sample_design',
        ),
    ]
