# Generated by Django 2.1.15 on 2020-01-20 18:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_sample_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample_design',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, null=True, size=5),
        ),
    ]
