# Generated by Django 2.1.15 on 2020-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200120_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample_design',
            field=models.TextField(default=None),
        ),
    ]
