# Generated by Django 2.1.15 on 2020-01-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200121_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleStrata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('FRQ', 'FRQ'), ('BAF', 'BAF')], default=None, max_length=3)),
                ('factor', models.IntegerField()),
                ('var', models.CharField(default=None, max_length=3)),
                ('minv', models.FloatField()),
                ('maxv', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='sample_design',
        ),
        migrations.AddField(
            model_name='samplestrata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_strata', to='core.Project'),
        ),
    ]
