# Generated by Django 2.1.15 on 2020-01-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200121_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('FRQ', 'FRQ'), ('BAF', 'BAF')], default=None, max_length=3)),
                ('factor', models.IntegerField()),
                ('var', models.CharField(default=None, max_length=3)),
                ('minv', models.FloatField()),
                ('maxv', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_design', to='core.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='samplestrata',
            name='project',
        ),
        migrations.DeleteModel(
            name='SampleStrata',
        ),
    ]
