# Generated by Django 2.1.15 on 2020-01-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200127_2229')
    ]

    operations = [
    ]
