# Generated by Django 2.1.15 on 2020-01-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200128_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treereference',
            name='max_density_index',
            field=models.IntegerField(default=None),
        ),
    ]
