# Generated by Django 2.1.15 on 2020-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200128_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treereference',
            name='max_density_index',
            field=models.IntegerField(null=True),
        ),
    ]
