# Generated by Django 2.1.15 on 2020-02-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200130_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treereference',
            name='family',
        ),
        migrations.RemoveField(
            model_name='treereference',
            name='max_density_index',
        ),
    ]
