# Generated by Django 2.1.15 on 2020-02-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200225_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='identification',
        ),
    ]
